version: '3'

services:
    php:
        image: php:7.2-apache
        volumes:
            - .:/var/www/html
        ports:
            - 80:80
        container_name: php7.2-trial2
    mysql:
        image: mysql:5.7
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=sample
            - MYSQL_USER=sample
            - MYSQL_PASSWORD=sample
        container_name: mysql5.7-trial2